# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - myhmdm-webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
        
      - name: Install tool
        run: |
          sudo apt-get update
          sudo apt install -y aapt tomcat9 postgresql vim certbot unzip net-tools
          
      - name: try upgraph sh
        run: chmod +x hmdm_install_2.sh
        
      - name: try create war with database
        run: sudo ./hmdm_install_2.sh
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: |
                /home/runner/work/myh-mdm/myh-mdm/common/target/commom-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/jwt/target/jwt-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/notification/target/notification-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/plugins/audit/target/audit-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/plugins/deviceinfo/target/deviceinfo-0.1.0.jpush-0.1.0ar
                /home/runner/work/myh-mdm/myh-mdm/plugins/devicelog/core/target/devicelog-core-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/plugins/devicelog/postgres/target/devicelog-postgres-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/plugins/messaging/target/messaging-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/plugins/platform/target/platform-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/plugins/push/target/push-0.1.0.jar
                /home/runner/work/myh-mdm/myh-mdm/server/target/launcher.war
                /home/runner/work/myh-mdm/myh-mdm/swagger/ui/target/mdm-swagger-ui-0.1.0.war
                /home/runner/work/myh-mdm/myh-mdm/ROOT.war
                /home/runner/work/myh-mdm/myh-mdm/ROOT.xml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myhmdm-webapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BC593CE2BA6A4E85B59E0DE2A38D6838 }}
          package: /home/runner/work/myh-mdm/myh-mdm/ROOT.war
